### ISSUE TITLE
Subscription examples from documentation throw errors

### ISSUE THREAD

**Issue by khyberspache** [microsoftgraph/msgraph-sdk-python#330]
I am trying to create a subscription to Security Events and followed the documentation here:
* https://learn.microsoft.com/en-us/graph/change-notifications-delivery-webhooks?tabs=python
* https://learn.microsoft.com/en-us/graph/webhooks

I am able to retrieve a Token, but every time I attempt to build the subscription, I receive a 400 stating “expirationDateTime must be provided with the subscription.”

```
from datetime import datetime, timedelta

graph_client = GraphServiceClient()

request_body = Subscription(
	change_type = "created",
	notification_url = "<MyApi>",
	lifecycle_notification_url = "<MyApi>",
	resource = "/security/alerts_v2",
	expiration_date_time = datetime.utcnow() + timedelta(days=3),
	client_state = "SecretClientState",
)

result = await graph_client.subscriptions.post(body = request_body)
```

**Comment by samwelkanda** [comment]
Hi @khyberspache 

Thanks for reporting this issue. This was a bug affecting POST/PUT/PATCH requests due to the way we track changes to models in our abstractions library.

Updating to `microsoft-kiota-abstractions==0.8.5` should fix the issue.
Thanks

**Comment by khyberspache** [comment]
@samwelkanda I’m going to test this out today and let you know if it works.

**Comment by khyberspache** [comment]
Still not working for me. Pip freeze:
```
aiohttp==3.8.5
aiosignal==1.3.1
anyio==4.0.0
asttokens==2.4.0
async-timeout==4.0.3
attrs==23.1.0
azure-core==1.29.4
azure-identity==1.14.0
backcall==0.2.0
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
crowdstrike-falconpy==1.3.2
cryptography==41.0.3
decorator==5.1.1
Deprecated==1.2.14
executing==1.2.0
frozenlist==1.4.0
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.18.0
httpx==0.25.0
hyperframe==6.0.1
idna==3.4
importlib-metadata==6.8.0
ipython==8.15.0
jedi==0.19.0
matplotlib-inline==0.1.6
microsoft-kiota-abstractions==0.8.5
microsoft-kiota-authentication-azure==0.3.0
microsoft-kiota-http==0.6.0
microsoft-kiota-serialization-json==0.4.0
microsoft-kiota-serialization-text==0.2.1
msal==1.24.0
msal-extensions==1.0.0
msgraph-core==1.0.0a4
msgraph-sdk==1.0.0a15
multidict==6.0.4
opentelemetry-api==1.20.0
opentelemetry-sdk==1.20.0
opentelemetry-semantic-conventions==0.41b0
parso==0.8.3
partners @ file:///workspaces/service/vendor/partners
pexpect==4.8.0
pickleshare==0.7.5
portalocker==2.8.2
prelude-sdk==1.4.11
prompt-toolkit==3.0.39
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.16.1
PyJWT==2.8.0
python-dateutil==2.8.2
requests==2.31.0
six==1.16.0
sniffio==1.3.0
stack-data==0.6.2
std-uritemplate==0.0.40
traitlets==5.10.0
typing_extensions==4.8.0
urllib3==2.0.4
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zipp==3.16.2
```

Tried both of these:
```
s = Subscription(change_type='created', notification_url='https://<redacted>/partner/suppress/2/21b62eb3c1b9c7732e429e08e716fee8', lifecycle_notification_url='https://<redacted>/partner/suppress/2/21b62eb3c1b9c7732e429e08e716fee8', resource="security/alerts?$filter=Status eq 'NewAlert' or Status eq 'InProgress' or Status eq 'Unknown' or Status eq 'Resolved'", expiration_date_time=(datetime.utcnow()+timedelta(days=3)).isoformat(), client_state='client_state')

await client.subscriptions.post(body=s)
```
```
ODataError: 
        APIError
        Code: 400
        message: None
        error: MainError(additional_data={}, code='InvalidRequest', details=None, inner_error=InnerError(additional_data={'date': datetime.timedelta(seconds=57759)}, client_request_id='2a052f2e-658c-4a2d-a4f2-e7667abeb2e4', date=None, odata_type=None, request_id='c8a1bc90-3cf0-471f-a77d-0698cacf424f'), message='expirationDateTime is a required property for subscription creation.', target=None)
```

```
s = Subscription(change_type='created', notification_url='https://<redacted>/partner/suppress/2/21b62eb3c1b9c7732e429e08e716fee8', lifecycle_notification_url='https://<redacted>/partner/suppress/2/21b62eb3c1b9c7732e429e08e716fee8', resource="security/alerts?$filter=Status eq 'NewAlert' or Status eq 'InProgress' or Status eq 'Unknown' or Status eq 'Resolved'", expiration_date_time=datetime.utcnow()+timedelta(days=3), client_state='client_state')

await client.subscriptions.post(body=s)
```
```
ODataError: 
        APIError
        Code: 400
        message: None
        error: MainError(additional_data={}, code='InvalidRequest', details=None, inner_error=InnerError(additional_data={'date': datetime.timedelta(seconds=60338)}, client_request_id='c894005f-dd34-4b59-b283-58bd136dc162', date=None, odata_type=None, request_id='583ced74-cc3b-4dd7-a449-88759588222d'), message='Could not process subscription creation payload. Are all property names spelled and camelCased properly?Also are the dateTimeOffest properties in a valid internet Date and Time format?', target=None)

```

**Comment by samwelkanda** [comment]
@khyberspache 

Found the bug that was causing this. Our serialization library wasn't processing strings for `datetime` values.

Please update to `microsoft-kiota-serialization-json 0.4.1 `. Valid datetime strings should now be serialized correctly.

Thanks.

**Comment by khyberspache** [comment]
@samwelkanda I will test this out tomorrow, thanks!
