### ISSUE TITLE
Issues with `CopyRequestBuilder.post()` and `to_post_request_information()` on several RequestBuilder classes

### ISSUE THREAD

**Issue by aberezh** [microsoftgraph/msgraph-sdk-python#334]
I’ve encountered two issues while working with the Drive functionality of `msgraph-sdk-python`.

1. The first one was simple to investigate and seems to be easy to fix. The `CopyRequestBuilder.post()` method calls the `self.request_adapter.send_async()` https://github.com/microsoftgraph/msgraph-sdk-python/blob/d50aa613c79b9401aec94c7416ba5c4e79f43bca/msgraph/generated/drives/item/items/item/copy/copy_request_builder.py#L53 method expecting a `DriveItem` as a response, while the `Copy a DriveItem REST API` [doesn’t return anything](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_copy#response). So I believe the fix should be simply to:
```python
# replace this
return await self.request_adapter.send_async(request_info, DriveItem, error_mapping)
# with this
return await self.request_adapter.send_no_response_content_async(request_info, error_mapping)
```

2. The second one is more tricky and I didn’t manage to get to the bottom of it in a reasonable amount of time. When the `to_post_request_information()` method is called on several RequestBuilder classes the `request_info.set_content_from_parsable()` does not actually set the content on `RequestInfo` (I ran into this with `CopyRequestBuilder` and `ChildrenRequestBuilder`)
https://github.com/microsoftgraph/msgraph-sdk-python/blob/d50aa613c79b9401aec94c7416ba5c4e79f43bca/msgraph/generated/drives/item/items/item/copy/copy_request_builder.py#L73 https://github.com/microsoftgraph/msgraph-sdk-python/blob/d50aa613c79b9401aec94c7416ba5c4e79f43bca/msgraph/generated/drives/item/items/item/children/children_request_builder.py#L130
As far as I’ve understood after digging into it, the issue lies in the `JsonSerializationWriter._serialize_value()` method, more specifically with [JsonSerializationWriter.on_before_object_serialization()](https://github.com/microsoft/kiota-serialization-json-python/blob/703495890bc8190c19c358ba9097e7b2f6283be6/kiota_serialization_json/json_serialization_writer.py#L402) method. But I may be wrong.

Would anyone be able to investigate/fix these issues any time soon?

**Comment by samwelkanda** [comment]
Hi @aberezh 

This was a bug in the way we track changes to models in our abstractions library

Updating to `microsoft-kiota-abstractions==0.8.5` should fix the issues
Thanks

**Comment by samwelkanda** [comment]
Closing for now. Feel free to re-open if the issue is not resolved.

**Comment by aberezh** [comment]
Hello @samwelkanda.

Thank you for your response! I can confirm that the second issue was fixed after updating the packages.

-----

However, the first issue still persists. I can see that the line I pointed out still has the bug.

To elaborate on the issue, when I make a copy request `CopyRequestBuilder(...).post(...)` I get a `DeserializationError`:

```python
Traceback (most recent call last)
----> 1 await client.drives.by_drive_id("drive_id").items.by_drive_item_id("item_to_copy").copy.post(copy_body)

File /usr/local/lib/python3.11/site-packages/msgraph/generated/drives/item/items/item/copy/copy_request_builder.py:53, in CopyRequestBuilder.post(self, body, request_configuration)
     50     raise Exception("Http core is null")
     51 from ......models.drive_item import DriveItem
---> 53 return await self.request_adapter.send_async(request_info, DriveItem, error_mapping)

File /usr/local/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py:176, in HttpxRequestAdapter.send_async(self, request_info, parsable_factory, error_map)
    174 if self._should_return_none(response):
    175     return None
--> 176 root_node = await self.get_root_parse_node(response, parent_span, parent_span)
    177 _deserialized_span = self._start_local_tracing_span("get_object_value", parent_span)
    178 value = root_node.get_object_value(parsable_factory)

File /usr/local/lib/python3.11/site-packages/kiota_http/httpx_request_adapter.py:396, in HttpxRequestAdapter.get_root_parse_node(self, response, parent_span, attribute_span)       
    394     response_content_type = self.get_response_content_type(response)
    395     if not response_content_type:
--> 396         raise DeserializationError("No response content type found for deserialization")
    397     return self._parse_node_factory.get_root_parse_node(response_content_type, payload)
    398 finally:

DeserializationError: No response content type found for deserialization
```

I already wrote this in the issue itself, but let me copy it here for visibility. I believe the issue is that the `CopyRequestBuilder.post()` method calls the `self.request_adapter.send_async()` https://github.com/microsoftgraph/msgraph-sdk-python/blob/9c0cedb8a2f494287074a31ea33ba7ba1149eec2/msgraph/generated/drives/item/items/item/copy/copy_request_builder.py#L53 method expecting a `DriveItem` as a response, while the `Copy a DriveItem REST API` [returns an empty response](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_copy#response). So I believe the fix should be simply to:
```python
# replace this
return await self.request_adapter.send_async(request_info, DriveItem, error_mapping)
# with this
return await self.request_adapter.send_no_response_content_async(request_info, error_mapping)
```

**Comment by GeorgePals** [comment]
Any updates on the first issue?

I'm trying to copy a folder, however I'm getting a 'None' response. Thus, I cannot check the creation progress or retrieve any request identifier. I would not like to use any workarounds.

```
copied_dir_res = await client.drives.by_drive_id(drive_id).items.by_drive_item_id(to_copy_directory_id).copy.post(copy_request_body)
```

Thanks!
